# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '94d1bc64-edde-49db-857f-6a4261c6c6bf'
  imageRepository: 'akaunting'
  containerRegistry: 'akaunting.azurecr.io'
  dockerfilePath: '**/Dockerfile' #'$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest' #'$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadSecureFile@1
      name: env_files
      inputs: 
        secureFile: '.env'
    
    - script: |           
        cp $(env_files.secureFilePath) .    
    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        #repository: $(imageRepository)
        repository: 'akaunting'
        #dockerfile: $(dockerfilePath)
        Dockerfile: '**/Dockerfile'        
        #containerRegistry: $(dockerRegistryServiceConnection)
        containerRegistry: 'Container Registry'
        tags: |
          $(tag)
    