version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: php
    container_name: app
    restart: always 
    tty: true
    ports:
      - "80:80"    
    networks:
      - app-network
    depends_on: 
      - db
    volumes:
      - ./data:/srv                
    #command: php artisan install --db-host=${DB_HOST} --db-port=${DB_PORT} --db-name=${DB_DATABASE} --db-username=${DB_USERNAME} --db-password=${DB_PASSWORD} --admin-email=${ADMIN_USER} --admin-password=${ADMIN_PASSWORD}
    env_file: .env

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file: .env.mysql 
    volumes:
      - ./data:/srv
      - ./data/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf       
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: akaunting-network
#Volumes
volumes:
  dbdata:
    driver: local