version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always 
    tty: true
    ports:
      - "80:80"    
    volumes:
      - ./data:/srv                  
    networks:
      - app-network
    env_file: .env  

#Docker Networks
networks:
  app-network:  
    driver: host

 